/* Run against an isolated, fresh demo instance; no external accounts are used. */
const { chromium, request } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');

(async () => {
  const baseURL = `http://127.0.0.1:${process.env.FILO_PORT || '8002'}`;
  const anonymous = await request.newContext({ baseURL });
  assert.equal((await anonymous.get('/api/bootstrap')).status(), 401);
  assert.equal((await anonymous.get('/api/agenda/export')).status(), 401);
  assert.equal((await anonymous.get('/api/health')).status(), 200);
  await anonymous.dispose();
  const browser = await chromium.launch({ executablePath: process.env.FILO_CHROMIUM_PATH || '/usr/bin/chromium', headless: true, args: ['--no-sandbox'] });
  try {
    const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, locale: 'it-IT', timezoneId: 'America/Los_Angeles', httpCredentials: { username: 'filo', password: 'morning-test' } });
    await context.grantPermissions(['clipboard-read', 'clipboard-write']);
    const page = await context.newPage();
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    await page.goto(baseURL);
    await page.waitForSelector('#app-content:not([hidden])');
    const state = () => page.evaluate(async () => (await fetch('/api/bootstrap')).json());
    const click = action => page.locator(`[data-action="${action}"]:visible`).first().click();
    let data = await state();
    assert.equal(data.runs.length, 0);
    assert.equal(data.briefing.status, 'not_started');
    assert.equal(data.briefing_example, null);
    assert.equal(await page.locator('.priority-item').count(), 0);
    assert.equal(await page.locator('#briefing-title').innerText(), 'Il riepilogo');

    const today = data.agenda.date;
    const addAppointment = async (title, day, time) => {
      await page.locator('#agenda-add > summary').click();
      await page.locator('#agenda-event-title').fill(title);
      await page.locator('#agenda-event-date').fill(day);
      await page.locator('#agenda-event-time').fill(time);
      await page.locator('#agenda-event-notes').fill('Porta il brief e i punti da discutere.');
      await page.locator('#agenda-form button[type=submit]').click();
      await page.waitForFunction(() => !document.querySelector('#agenda-add').open);
      await page.waitForFunction(title => [...document.querySelectorAll('.agenda-event h3')].some(node => node.textContent === title), title);
    };
    await addAppointment('Incontro con Giulia', today, '09:30');
    data = await state();
    assert.equal(data.agenda.items[0].time_label, '09:30', 'Input must use Rome even with a US browser timezone.');
    await addAppointment('Preparazione preventivo', today, '08:30');
    assert.equal(await page.locator('.agenda-time').first().innerText(), '08:30');
    const downloadPromise = page.waitForEvent('download');
    await page.locator('#agenda-export').click();
    const download = await downloadPromise;
    assert.equal(download.suggestedFilename(), `ordine-del-giorno-${today}.txt`);
    await download.saveAs('.runtime/morning-order-of-day.txt');
    const exported = await fs.readFile('.runtime/morning-order-of-day.txt', 'utf8');
    assert.match(exported, /08:30 — Preparazione preventivo/);
    assert.match(exported, /09:30 — Incontro con Giulia/);
    const tomorrow = new Date(new Date(`${today}T12:00:00Z`).valueOf() + 86400000).toISOString().slice(0, 10);
    await addAppointment('Incontro di domani', tomorrow, '14:00');
    assert.equal(await page.locator('#agenda-view-date').inputValue(), tomorrow);
    assert.equal(await page.locator('.agenda-event').count(), 1);
    await page.locator('#agenda-view-date').fill(today);
    await page.waitForFunction(() => document.querySelectorAll('.agenda-event').length === 2);
    await page.reload();
    await page.waitForSelector('#app-content:not([hidden])');
    assert.equal(await page.locator('.agenda-event').count(), 2);

    await click('open-wizard');
    await click('wizard-next');
    await click('connect-demo');
    await click('wizard-next');
    await click('wizard-preview');
    await page.waitForSelector('.preview-item');
    await click('wizard-next');
    await page.locator('#authorize-read').check();
    await page.locator('#authorize-draft').check();
    await click('wizard-activate');
    await click('wizard-finish');
    await click('run');
    await page.waitForFunction(async () => (await (await fetch('/api/bootstrap')).json()).briefing.status === 'ready');
    await page.waitForFunction(() => document.querySelector('#briefing-period').textContent.includes('FITTIZIE') === false && document.querySelectorAll('.priority-item').length === 3);
    assert.equal((await state()).briefing_example, null);
    const first = page.locator('.priority-item').first();
    const firstClient = await first.locator('.priority-meta strong').innerText();
    assert.match(firstClient, /Giulia|Marco|Sara/);
    await page.locator('#suggestion-card [data-action="review-priority"]').click();
    assert.equal(await first.locator('details').getAttribute('open'), '');
    await page.waitForTimeout(5300);
    assert.equal(await first.locator('details').getAttribute('open'), '');
    await first.locator('[data-action="copy-priority"]').click();
    assert.match(await page.evaluate(() => navigator.clipboard.readText()), /Ciao/);
    await first.locator('[data-action="approve-draft"]').click();
    await page.waitForFunction(() => document.querySelectorAll('.priority-item').length === 2);
    assert.equal(await page.locator('#detail-dialog').getAttribute('open'), null);
    await click('run');
    await page.waitForFunction(async () => (await (await fetch('/api/bootstrap')).json()).runs.filter(run => run.status === 'succeeded').length >= 2);
    await page.waitForTimeout(5300);
    assert.equal(await page.locator('.priority-item').count(), 2, 'Repeated demo checks must not duplicate or resurrect reviewed sources.');
    await page.evaluate(() => window.scrollTo(0, 0));
    await page.screenshot({ path: '.runtime/morning-active-desktop.png', fullPage: true });
    await page.setViewportSize({ width: 390, height: 844 });
    await page.screenshot({ path: '.runtime/morning-active-mobile.png', fullPage: true });
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Mobile must not overflow.');
    assert.deepEqual(errors, []);
    console.log('PASS: password, empty initial state, persistent drafts during polling, morning priorities, revision and duplicate suppression, Rome agenda with US browser, persistence, daily navigation and downloadable report; desktop/mobile without JS errors or overflow.');
    await context.close();
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
